import { describe, expect, it } from "vitest";
import { verifyWebhookSignature } from "../src/webhooks.js";

/**
 * Cross-implementation fixture: this exact (secret, payload, timestamp) ->
 * signature triple was generated by the Rust backend's
 * `webhooks::generate_webhook_signature` (see the matching Rust-side test
 * `generate_webhook_signature_matches_sdk_fixture` in src/webhooks.rs).
 * Keeping the fixture identical on both sides is how Property 28
 * ("Webhook signatures round-trip identically between backend and SDK",
 * Requirements 6.7/6.14) is verified without spinning up the Rust backend
 * in this test suite.
 */
const FIXTURE_SECRET = "whsec_a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2";
const FIXTURE_PAYLOAD =
  '{"event":"payment_request_succeeded","payment_request":{"id":"abc123","amount_usdc":10.5,"description":null,"status":"paid"},"timestamp":"2023-11-14T22:13:20Z"}';
const FIXTURE_TIMESTAMP = 1700000000;
const FIXTURE_SIGNATURE_HEADER =
  "t=1700000000,v1=033fc6070d24e364d2a644010d0f62f56dd0fac39c1e2c8d824c5e45c5a6b1eb";

describe("verifyWebhookSignature", () => {
  it("accepts a signature generated by the Rust backend for the same payload/secret", () => {
    // Since the fixture timestamp is fixed in the past, we must pass a
    // tolerance large enough to cover "now - fixture timestamp" — this is
    // purely a test artifact; production calls use the default 300s window
    // against a live timestamp.
    const nowSeconds = Math.floor(Date.now() / 1000);
    const toleranceSeconds = nowSeconds - FIXTURE_TIMESTAMP + 10;

    const valid = verifyWebhookSignature(
      FIXTURE_PAYLOAD,
      FIXTURE_SIGNATURE_HEADER,
      FIXTURE_SECRET,
      toleranceSeconds,
    );
    expect(valid).toBe(true);
  });

  it("rejects when the payload is tampered with", () => {
    const nowSeconds = Math.floor(Date.now() / 1000);
    const toleranceSeconds = nowSeconds - FIXTURE_TIMESTAMP + 10;
    const tamperedPayload = FIXTURE_PAYLOAD.replace("10.5", "99.9");

    const valid = verifyWebhookSignature(
      tamperedPayload,
      FIXTURE_SIGNATURE_HEADER,
      FIXTURE_SECRET,
      toleranceSeconds,
    );
    expect(valid).toBe(false);
  });

  it("rejects when the secret is wrong", () => {
    const nowSeconds = Math.floor(Date.now() / 1000);
    const toleranceSeconds = nowSeconds - FIXTURE_TIMESTAMP + 10;

    const valid = verifyWebhookSignature(
      FIXTURE_PAYLOAD,
      FIXTURE_SIGNATURE_HEADER,
      "whsec_0000000000000000000000000000000000000000000000000000000000000000",
      toleranceSeconds,
    );
    expect(valid).toBe(false);
  });

  it("rejects a malformed signature header", () => {
    expect(verifyWebhookSignature(FIXTURE_PAYLOAD, "not-a-valid-header", FIXTURE_SECRET)).toBe(false);
    expect(verifyWebhookSignature(FIXTURE_PAYLOAD, "t=123", FIXTURE_SECRET)).toBe(false);
    expect(verifyWebhookSignature(FIXTURE_PAYLOAD, "t=abc,v1=deadbeef", FIXTURE_SECRET)).toBe(false);
  });

  it("rejects when the signature is outside the tolerance window", () => {
    // Default tolerance (300s) is far smaller than "now - fixture timestamp",
    // so this must fail without an explicit generous tolerance override.
    const valid = verifyWebhookSignature(FIXTURE_PAYLOAD, FIXTURE_SIGNATURE_HEADER, FIXTURE_SECRET);
    expect(valid).toBe(false);
  });

  it("round-trips with a freshly generated signature using the same algorithm shape", () => {
    // Self-consistency check: a signature computed by re-deriving the HMAC
    // manually (mirroring the backend's approach) over a fresh timestamp
    // must verify successfully.
    const nowSeconds = Math.floor(Date.now() / 1000);
    const secretHex = FIXTURE_SECRET.slice("whsec_".length);
    const { createHmac } = require("node:crypto");
    const key = Buffer.from(secretHex, "hex");
    const signedPayload = `${nowSeconds}.${FIXTURE_PAYLOAD}`;
    const sigHex = createHmac("sha256", key).update(signedPayload, "utf8").digest("hex");
    const header = `t=${nowSeconds},v1=${sigHex}`;

    expect(verifyWebhookSignature(FIXTURE_PAYLOAD, header, FIXTURE_SECRET)).toBe(true);
  });
});
